spring:
  config:
    activate:
      on-profile: dev
  mail:
    protocol: smtp
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: from@example.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-doma2-sample?useSSL=false
    username: root
    password: passw0rd
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: false
logging:
  level:
    org.springframework: INFO
    com.bigtreetc.sample.batch: DEBUG


####
# アプリケーションの設定
application:
  fileUploadLocation: build/sample
