spring:
  profiles: stg
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-doma2-sample?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: passw0rd
  mail:
    protocol: smtp
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: from@test.com
logging:
  level:
    org.springframework.web: INFO

####
# アプリケーションの設定
application:
  fileUploadLocation: build/sample
